-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 20:33:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Door_Key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Door_Key` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Door_Key` (
  `Door_Key_ID` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Door_Key_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Door`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Door` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Door` (
  `Door_ID` INT NOT NULL AUTO_INCREMENT,
  `Code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Door_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Borrowing_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Borrowing_Status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Borrowing_Status` (
  `User_User_ID` INT NOT NULL,
  `Key_Key_ID` INT NOT NULL,
  `from` TIMESTAMP NULL,
  `to` TIMESTAMP NULL,
  `Borrowing_Status_ID` INT NOT NULL,
  PRIMARY KEY (`Borrowing_Status_ID`),
  CONSTRAINT `fk_User_has_Key_User`
    FOREIGN KEY (`User_User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Key_Key1`
    FOREIGN KEY (`Key_Key_ID`)
    REFERENCES `mydb`.`Door_Key` (`Door_Key_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Key_Key1_idx` ON `mydb`.`Borrowing_Status` (`Key_Key_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Key_User_idx` ON `mydb`.`Borrowing_Status` (`User_User_ID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Key2Door`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Key2Door` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Key2Door` (
  `Key_Key_ID` INT NOT NULL,
  `Door_Door_ID` INT NOT NULL,
  `Key2Door_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Key2Door_ID`),
  CONSTRAINT `fk_Key_has_Door_Key1`
    FOREIGN KEY (`Key_Key_ID`)
    REFERENCES `mydb`.`Door_Key` (`Door_Key_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Key_has_Door_Door1`
    FOREIGN KEY (`Door_Door_ID`)
    REFERENCES `mydb`.`Door` (`Door_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Key_has_Door_Door1_idx` ON `mydb`.`Key2Door` (`Door_Door_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Key_has_Door_Key1_idx` ON `mydb`.`Key2Door` (`Key_Key_ID` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
